### ISSUE TITLE
Application does not appear in application list on Windows

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#12]
After installation on Windows, the application does not appear in the start menu, making it quite hard to restart it. 

For reference, the actual executable is stored in `C:\Users\<user>\AppData\Local\gtt_taskbar`,

It does appear in the application list, so removing does work ;)

**Comment by kriskbx** [comment]
Should be fixed with 0.2.6. Can you try install it again?

**Comment by bobvandevijver** [comment]
It is now available in the installed application list (although it doesn't start, see #20). It is however still missing from the start menu.

**Comment by bobvandevijver** [comment]
Fixed with 0.3.0 👍
