### ISSUE TITLE
Time tracker always shows "a few seconds" as status

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#16]
Even though it has been some time, it only shown "a few seconds)
![image](https://user-images.githubusercontent.com/1835343/41501302-54cf81fc-71a2-11e8-95be-22a8030fd666.png)

The overview actually does not show any time.

![image](https://user-images.githubusercontent.com/1835343/41501317-778e0af6-71a2-11e8-8226-3fd3c5f1fc72.png)

**Comment by kriskbx** [comment]
Fixed in 0.2.5. Thanks for pointing it out!

**Comment by bobvandevijver** [comment]
This is not completely fixed: the "a few seconds" ago is still the only thing I see in the popup (first image). 

The log is fixed for the time, although the date is now fixed on "January 1st 2000".  It also doesn't show currently running time records.
