### ISSUE TITLE
Open animation is wonky

### ISSUE THREAD

**Issue by bobvandevijver** [kriskbx/gitlab-time-tracker-taskbar#21]
When opening the widget, it seems to be closing first, to directly open afterwards. This results in a flickering experience.

**Comment by kriskbx** [comment]
Fixed in 0.3.4. 😃

**Comment by kriskbx** [comment]
Thanks a lot for reporting stuff like this. The app gets better and better thanks to all testers and contributors like you. ❤️

**Comment by bobvandevijver** [comment]
I can still get it to happen sometimes, but it isn't nearly as annoying as it was. Good work! 👍
